export enum AuditAction {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  PERMISSION_CHANGED = 'PERMISSION_CHANGED',
  ASSIGNED = 'ASSIGNED',
  DECISION_MADE = 'DECISION_MADE',
  BUDGET_RELEASED = 'BUDGET_RELEASED',
  WORKSPACE_UNLOCKED = 'WORKSPACE_UNLOCKED',
  EVALUATOR_ASSIGNED = 'EVALUATOR_ASSIGNED',
  OTHER = 'OTHER',
}

export type AuditActionValue = `${AuditAction}`;
