export enum Permission {
  // Project creation and submission
  PROJECT_CREATE = 'PROJECT_CREATE',
  PROJECT_PRE_REGISTER = 'PROJECT_PRE_REGISTER',
  PROJECT_SUBMIT = 'PROJECT_SUBMIT',

  // Project review and approval
  PROJECT_REVIEW = 'PROJECT_REVIEW',
  PROJECT_APPROVE = 'PROJECT_APPROVE',
  PROJECT_REJECT = 'PROJECT_REJECT',
  PROJECT_RECOMMEND = 'PROJECT_RECOMMEND',

  // Budget management
  BUDGET_VIEW = 'BUDGET_VIEW',
  BUDGET_APPROVE = 'BUDGET_APPROVE',
  BUDGET_REJECT = 'BUDGET_REJECT',

  // Team management
  TEAM_MANAGE = 'TEAM_MANAGE',
  TEAM_VIEW = 'TEAM_VIEW',
  EVALUATOR_ASSIGN = 'EVALUATOR_ASSIGN',

  // Ethical clearance
  ETHICS_REVIEW = 'ETHICS_REVIEW',
  ETHICS_APPROVE = 'ETHICS_APPROVE',
  ETHICS_REJECT = 'ETHICS_REJECT',

  // Administrative
  ADMIN_VIEW = 'ADMIN_VIEW',
  ADMIN_EDIT = 'ADMIN_EDIT',
  CALENDAR_MANAGE = 'CALENDAR_MANAGE',

  // View permissions
  PROJECT_VIEW = 'PROJECT_VIEW',
  USER_VIEW = 'USER_VIEW',
}
